baseUrl: /
theme: terminal
paginate: 5
publishdir: docs
params:
      # dir name of your blog content (default is `content/posts`)
      contentTypeName: content
      # ["orange", "blue", "red", "green", "pink"]
      themeColor: orange
      # if you set this to 0, only submenu trigger will be visible
      showMenuItems: 5
      # show selector to switch language
      showLanguageSelector: false
      # set theme to full screen width
      fullWidthTheme: true
      # center theme with default width
      centerTheme: true
      showFullContent: true

